export const drinks = [
  // MILK TEAS (D300)
  {
    id: 1,
    name: "Classic Milk",
    slug: "classic-milk",
    price: 300,
    image: "/rose.png",
    category: "milktea",
  },
  {
    id: 2,
    name: "Brown Sugar Milk",
    slug: "brown-sugar-milk",
    price: 300,
    image: "/matcha.png",
    category: "milktea",
  },
  {
    id: 3,
    name: "Thai Milk",
    slug: "thai-milk",
    price: 300,
    image: "/thai.png",
    category: "milktea",
  },
  {
    id: 4,
    name: "Mango Milk",
    slug: "mango-milk",
    price: 300,
    image: "/rose.png",
    category: "milktea",
  },
  {
    id: 5,
    name: "Strawberry Milk",
    slug: "strawberry-milk",
    price: 300,
    image: "/rose.png",
    category: "milktea",
  },

  // FRUIT TEAS
  {
    id: 6,
    name: "Passion Fruit",
    slug: "passion-fruit",
    price: 300,
    image: "/thai.png",
    category: "fruittea",
  },
  {
    id: 7,
    name: "Strawberry Fruit Tea",
    slug: "strawberry-fruit-tea",
    price: 300,
    image: "/rose.png",
    category: "fruittea",
  },
  {
    id: 8,
    name: "Mango Fruit Tea",
    slug: "mango-fruit-tea",
    price: 300,
    image: "/rose.png",
    category: "fruittea",
  },
  {
    id: 9,
    name: "Jasmine Lemon",
    slug: "jasmine-lemon",
    price: 250,
    image: "/matcha.png",
    category: "fruittea",
  },
  {
    id: 10,
    name: "Wonjo",
    slug: "wonjo",
    price: 250,
    image: "/rose.png",
    category: "fruittea",
  },
  {
    id: 11,
    name: "Lemon & Mint Ice Tea",
    slug: "lemon-mint-ice-tea",
    price: 250,
    image: "/matcha.png",
    category: "fruittea",
  },
  {
    id: 12,
    name: "Smiling Coast (Wonjo & Mango)",
    slug: "smiling-coast",
    price: 300,
    image: "/rose.png",
    category: "fruittea",
  },

  // REFRESHERS / SPECIALS
  {
    id: 13,
    name: "Iced Latte",
    slug: "iced-latte",
    price: 300,
    image: "/matcha.png",
    category: "specials",
  },
  {
    id: 14,
    name: "Caramel/Vanilla Iced Latte",
    slug: "caramel-vanilla-latte",
    price: 350,
    image: "/matcha.png",
    category: "specials",
  },
  {
    id: 15,
    name: "Chai Masala Milk",
    slug: "chai-masala-milk",
    price: 300,
    image: "/thai.png",
    category: "specials",
  },
  {
    id: 16,
    name: "Matcha Milk",
    slug: "matcha-milk",
    price: 300,
    image: "/matcha.png",
    category: "specials",
  },
  {
    id: 17,
    name: "Taro Milk",
    slug: "taro-milk",
    price: 300,
    image: "/matcha.png",
    category: "specials",
    isSpecial: true,
  },
  {
    id: 18,
    name: "Strawberry Matcha",
    slug: "strawberry-matcha",
    price: 350,
    image: "/matcha.png",
    category: "specials",
  },
  {
    id: 19,
    name: "Baobab Milk",
    slug: "baobab-milk",
    price: 250,
    image: "/thai.png",
    category: "specials",
  },
  {
    id: 20,
    name: "Pink Paradise (Wonjo & Baobab)",
    slug: "pink-paradise",
    price: 250,
    image: "/rose.png",
    category: "specials",
  },
];
