export const drinks = [
  // MILK TEAS (D300)
  {
    id: 1,
    name: "Classic Milk",
    slug: "classic-milk",
    price: 300,
    image: "/classic.png",
    category: "milktea",
  },
  {
    id: 2,
    name: "Brown Sugar Milk",
    slug: "brown-sugar-milk",
    price: 300,
    image: "/BrownSuga.png",
    category: "milktea",
  },
  {
    id: 3,
    name: "Thai Milk",
    slug: "thai-milk",
    price: 300,
    image: "/thai.png",
    category: "milktea",
  },
  {
    id: 4,
    name: "Mango Milk",
    slug: "mango-milk",
    price: 300,
    image: "/mango.png",
    category: "milktea",
  },
  {
    id: 5,
    name: "Strawberry Milk",
    slug: "strawberry-milk",
    price: 300,
    image: "/strawberrymilk.png",
    category: "milktea",
  },

  // FRUIT TEAS
  {
    id: 6,
    name: "Passion Fruit",
    slug: "passion-fruit",
    price: 300,
    image: "/passion.png",
    category: "fruittea",
  },
  {
    id: 7,
    name: "Strawberry Fruit Tea",
    slug: "strawberry-fruit-tea",
    price: 300,
    image: "/strawberryfruit.png",
    category: "fruittea",
  },
  {
    id: 8,
    name: "Mango Fruit Tea",
    slug: "mango-fruit-tea",
    price: 300,
    image: "/mangofru.png",
    category: "fruittea",
  },
  {
    id: 9,
    name: "Jasmine Lemon",
    slug: "jasmine-lemon",
    price: 250,
    image: "/jasmine.png",
    category: "fruittea",
  },
  {
    id: 10,
    name: "Wonjo",
    slug: "wonjo",
    price: 250,
    image: "/wonjo.png",
    category: "fruittea",
  },
  {
    id: 11,
    name: "Lemon & Mint Ice Tea",
    slug: "lemon-mint-ice-tea",
    price: 250,
    image: "/lemon.png",
    category: "fruittea",
  },
  {
    id: 12,
    name: "Smiling Coast (Wonjo & Mango)",
    slug: "smiling-coast",
    price: 300,
    image: "/rose.png",
    category: "fruittea",
  },

  // REFRESHERS / SPECIALS
  {
    id: 13,
    name: "Iced Latte",
    slug: "iced-latte",
    price: 300,
    image: "/icedlatte.png",
    category: "specials",
  },
  {
    id: 14,
    name: "Caramel/Vanilla Iced Latte",
    slug: "caramel-vanilla-latte",
    price: 350,
    image: "/Caramel.png",
    category: "specials",
  },
  {
    id: 15,
    name: "Chai Masala Milk",
    slug: "chai-masala-milk",
    price: 300,
    image: "/chai.png",
    category: "specials",
  },
  {
    id: 16,
    name: "Matcha Milk",
    slug: "matcha-milk",
    price: 300,
    image: "/matcha.png",
    category: "specials",
  },
  {
    id: 17,
    name: "Taro Milk",
    slug: "taro-milk",
    price: 300,
    image: "/tero.png",
    category: "specials",
    isSpecial: true,
  },
  {
    id: 18,
    name: "Strawberry Matcha",
    slug: "strawberry-matcha",
    price: 350,
    image: "/strawberrymatcha.png",
    category: "specials",
  },
  {
    id: 19,
    name: "Baobab Milk",
    slug: "baobab-milk",
    price: 250,
    image: "/baobabmilk.png",
    category: "specials",
  },
  {
    id: 20,
    name: "Pink Paradise (Wonjo & Baobab)",
    slug: "pink-paradise",
    price: 250,
    image: "/pinkparadise.png",
    category: "specials",
  },
  {
    id: 21,
    name: "Ice Cream Boba",
    slug: "ice-cream-boba",
    price: 450,
    image: "/classic.png", // Placeholder image, using classic for now
    category: "specials",
    seasonal: true,
    seasonLabel: "Special Offer 🍦",
    offerLabel: "Buy 1 Get 1 Free",
    availableFrom: "2026-03-14", // Starting today
    availableTo: "2026-04-14",   // 1 month offer
  },
  {
    id: 22,
    name: "Belgian Waffle",
    slug: "belgian-waffle",
    price: 300,
    image: "/classic.png",
    category: "snacks",
    description: "Crispy on the outside, fluffy on the inside. Served with your choice of syrup.",
  },
  {
    id: 23,
    name: "Vanilla Ice Cream",
    slug: "vanilla-ice-cream",
    price: 300,
    image: "/classic.png",
    category: "snacks",
    description: "Creamy, classic vanilla bean ice cream.",
  },
  {
    id: 24,
    name: "Chocolate Ice Cream",
    slug: "chocolate-ice-cream",
    price: 300,
    image: "/classic.png",
    category: "snacks",
    description: "Rich and decadent dark chocolate ice cream.",
  },
  {
    id: 25,
    name: "Strawberry Ice Cream",
    slug: "strawberry-ice-cream",
    price: 300,
    image: "/classic.png",
    category: "snacks",
    description: "Sweet strawberry ice cream with real fruit chunks.",
  },
];
